### ISSUE TITLE
Tracking issue for using rust-fmt

### ISSUE THREAD

**Issue by Susurrus** [retep998/winapi-rs#444]
If rust-fmt could follow the style guidelines, it'd make much of this library development easier. This issue will track the work necessary to get rust-fmt suitable for automatically formatting code.

- [ ] Fix bug where rustfmt doesn't put the first parameter on a newline (rust-lang-nursery/rustfmt#1508)
- [ ] Specify rules on trailing commas on the last argument to function calls
- [ ] Disable formatting of macros in rustfmt

I think that's everything. @retep998 Can you clarify the 2nd point? Right now if you use `rustfmt` it will remove the trailing comma from the last argument to a function. Is that acceptable or not?
