### ISSUE TITLE
winapi 0.4 tracking issue

### ISSUE THREAD

**Issue by retep998** [retep998/winapi-rs#885]
* [ ] Upgrade minimum Rust version to 1.33
* [ ] Add `#[repr(packed(N))]` everywhere applicable.
* [ ] Add `#[repr(align(N))]` everywhere applicable.
* [ ] Use actual unions for unions.
* [ ] Use nested imports.
* [ ] Upgrade to 2018 edition.
* [ ] Merge any pull requests that have breaking changes.
* [ ] Switch to [`FlexibleArray`](https://gist.github.com/rust-play/a0faca71829d3af39da4910ac9a11e30).
  * Due to needing to preserve the distinction between `[T;0]` and `[T; 1]`, it may be better to just tell people to use `VariableSizedBox`.
* [ ] Fix any deprecation warnings.
* [ ] Replace macro functions with actual const functions.
* [ ] Figure out better way to define strings.
* [ ] Get rustfmt working maybe

**Comment by euclio** [comment]
Would you accept PRs tackling these issues against the `dev` branch?

**Comment by retep998** [comment]
The `dev` branch is where I write my own commits for testing on CI before merging them into a mainline branch. I'll eventually create a `0.4` branch where 0.4 specific changes can be directed.
