### ISSUE TITLE
[Secretary] Work Tracker

### ISSUE THREAD

**Issue by Lokathor** [retep998/winapi-rs#886]
# Waiting On Author
* [ ] Add isolation aware support to 0.2 branch, updated on Aug 27, 2019
* [ ] missing DXGI_MWA_* constants, updated on Aug 28, 2019
* [ ] Add msdelta, updated on Aug 28, 2019
* [ ] Adding PROC_THREAD_ATTRIBUTE_* constants, updated on Aug 28, 2019
* [ ] Add audiopolicy, updated on Aug 28, 2019
* [ ] Add ntddstor definitions, updated on Aug 28, 2019
* [ ] Migrate wincodec APIs, updated on Aug 28, 2019
* [ ] Add objidl definitions, updated on Aug 28, 2019
* [ ] Migrate traffic APIs, updated on Aug 28, 2019
* [ ] Migrate event APIs, updated on Aug 28, 2019
* [ ] Update mmsystem header to latest SDK version, updated on Aug 28, 2019
* [ ] RFC: Add Windows Hypervisor Platform APIs, updated on Sep 13, 2019
* [ ] Add MessageBoxTimeoutA and MessageBoxTimeoutW, updated on Nov 11, 2019
* [ ] Add bindings to DirectShow stuff, updated on Dec 28, 2019

**Comment by Lokathor** [comment]
# Waiting on Review
<https://docs.google.com/spreadsheets/d/1ivR2LYCDBbXBsOCdjyE18OD7EGUQYAl1q2ivV6dRWSE/edit#gid=0>

**Comment by roblabla** [comment]
Here are some bindings addition PRs that were reviewed and approved by the community, and are ready to be merged. Those PRs contain no breaking change.
 
- #963 (based on #859 which was reviewed by retep)
- #962 (reviewed by @nico-abram)
- #960 (reviewed by @MaulingMonkey)
- #957 (reviewed by @MaulingMonkey)
- #952 (reviewed by @MaulingMonkey)
- #934 (reviewed by @MaulingMonkey)
- #931 (reviewed by @nico-abram)
- #925 (reviewed by @roblabla)
- #923 (reviewed by @roblabla)
- #906 (reviewed by @roblabla)
